convert some workflows to actions

diff --git a/.github/workflows/init-repository.yml b/.github/workflows/init-repository.yml
--- a/.github/workflows/init-repository.yml
+++ b/.github/workflows/init-repository.yml
@@ -56,7 +56,7 @@ jobs:
             SSH_AUTH_SOCK="$SSH_SOCK" GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=yes" git clone git@github.com:${GITHUB_REPOSITORY}.git -b "${GITHUB_HEAD_REF}" .
 
             git config merge.directoryRenames false
-            git fetch --tags --force
+            SSH_AUTH_SOCK="$SSH_SOCK" GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=yes" git fetch --tags --force
           else
             echo 'repository cache is already present, updating sources...'
             SSH_AUTH_SOCK="$SSH_SOCK" GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=yes" git fetch --tags --force
@@ -68,7 +68,40 @@ jobs:
           ### For Pull Request workflows in GitHub Actions, we need to test the merge result
           ### This is similar to GitLab's merged results pipelines
           if [ $GITHUB_BASE_REF ]; then
-            sh $WORKING_DIRECTORY/.github/actions/init/init-merge-result-pipeline.sh
+            echo "Merge $GITHUB_BASE_REF into $WORKING_DIRECTORY to allow a merge result pipeline"
+
+            # attempt to merge
+            git merge --no-commit --no-ff origin/$GITHUB_BASE_REF
+
+            # if merge conflict detected
+            if [ $? -ne 0 ]; then
+              echo "################################################################################################"
+              echo "################################################################################################"
+              echo "################################################################################################"
+              echo ""
+              echo "Merge conflict detected:"
+              echo "Resolve them by merging $GITHUB_BASE_REF into $GITHUB_HEAD_REF and push changes."
+              echo ""
+              echo "################################################################################################"
+              echo "################################################################################################"
+              echo "################################################################################################"
+
+              echo "Resetting and make the pipeline fail to handle conflicts..."
+
+              git merge --abort
+
+              echo "Add a comment to PR to notify assignee"
+            ADD_THREAD=$(curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
+              --data "{\"body\": \" :warning: Conflicts detected, resolve them by merging \`${GITHUB_BASE_REF}\` into \`${GITHUB_HEAD_REF}\` and then push changes.\"}" \
+              --header "Content-Type: application/json" \
+              --header "Authorization: token $GITHUB_TOKEN" \
+              --request POST \
+              "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${GITHUB_EVENT_NUMBER}/comments")
+
+              exit 1
+            else
+              echo "No conflicts, continue pull request pipeline"
+            fi
           fi
 
           ### Never init cache for tag pipelines that are only triggered to promote a rc tag to a release tag
